### ISSUE TITLE
Add ._* to .gitignore

### ISSUE THREAD

**Issue by aj-foster** [ucf-design-group/vucf#1]
Probably something I should have documented: the Samba file shares that let you work on dev/live from the Mac will fill your repositories with ._ files. Might want to remove and ignore them.

That was just an excuse to make an issue, really. Hope you folks are doing well.

**Comment by ghost** [comment]
Thank you so much, that was an issue I spent like a day working on haha. I'll add it to the docs

Sent from my T-Mobile 4G LTE Device-------- Original message --------From: AJ Foster notifications@github.com Date: 3/1/2016  1:50 PM  (GMT-05:00) To: ucf-design-group/vucf vucf@noreply.github.com Subject: [vucf] Add ._\* to .gitignore (#1) 
Probably something I should have documented: the Samba file shares that let you work on dev/live from the Mac will fill your repositories with ._ files. Might want to remove and ignore them.

That was just an excuse to make an issue, really. Hope you folks are doing well.

**Comment by billcolumbia** [comment]
:open_mouth:

**Comment by aj-foster** [comment]
👻 The ghosts of DG past have appeared.

**Comment by billcolumbia** [comment]
@aj-foster sneaky 🐍

**Comment by aj-foster** [comment]
Just looked at all of my open issues and thought, what is this garbage?
